### ISSUE TITLE
[Question] How can I use bf16 as inference precision for LLM?

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#164]
As Title

**Comment by yuxu42** [comment]
The assumption is that HW you're using has the BF16 capability, such as Sapphire Rapids, Emerald Rapids, so that you can get the performance benefit from BF16 HW via OpenVINO SW. 
OpenVINO has the logic to detect the HW capablity. If there is native BF16 HW capability, it will automatically infer with BF16 inference precision for both LLM and non-LLM models.

**Comment by JunxiChhen** [comment]
OK, that means the default precision is bf16. But how can I switch to other precisions such as fp32?

**Comment by yuxu42** [comment]
You can refer to the documentation for OpenVINO [inference precision hint setting](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_supported_plugins_CPU.html#inference-precision-hint ).

**Comment by JunxiChhen** [comment]
Thanks.
