### ISSUE TITLE
ChatGLM3 output token size is not generated as expected

### ISSUE THREAD

**Issue by JunxiChhen** [openvinotoolkit/openvino.genai#390]
Benchmark cmd (-ic is 128):
```
numactl -C 0-55 -m 0 python benchmark.py     -m /root/.cache/huggingface/hub/chatglm3-6b-ov/pytorch/dldt/FP16     -p "It is done, and submitted..."     -n 2     -bs 1     -d CPU --torch_compile_backend openvino     -ic 128 --num_beams 1 -lc bfloat16_config.json 2>&1 | tee -a ./logs/0.log
```
![image](https://github.com/openvinotoolkit/openvino.genai/assets/92417411/4155e768-6fc2-4a87-bb97-37ebbd8b65a1)

BTW, ChatGLM2's output size is right.

**Comment by peterchen-intel** [comment]
@JunxiChhen The reason is that ChatGLM3 gives "end token" at output size 17 with the input prompt. The WA is to update prompt to let ChatGLM3 generate more tokens (>=128).
-ic means the maximum output token size (or maximum inference number).
There is a ongoing https://github.com/openvinotoolkit/openvino.genai/pull/289 which is trying to "force" generate expected output size even "end token" is given.

**Comment by peterchen-intel** [comment]
@JunxiChhen PR has been merged. Please verify.

**Comment by yangkunx** [comment]
When I update the  latest commit id, run case with blew error:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/122254299/1992f342-97f2-4c04-9bf9-ce969170d671)

**Comment by peterchen-intel** [comment]
@yangkunx This new issue should be fixed by [PR#435](https://github.com/openvinotoolkit/openvino.genai/pull/435)

**Comment by peterchen-intel** [comment]
https://github.com/openvinotoolkit/openvino.genai/pull/289  was just reverted, due to the performance impact. New PR https://github.com/openvinotoolkit/openvino.genai/pull/457 is WIP

**Comment by peterchen-intel** [comment]
New PR https://github.com/openvinotoolkit/openvino.genai/pull/457 was merged. @yangkunx  @JunxiChhen  please verify.
