### ISSUE TITLE
fbgemm.dll missing while running benchmark.py

### ISSUE THREAD

**Issue by avinashbhat09** [openvinotoolkit/openvino.genai#813]
While running benchmark.py getting fbgemm.dll missing. This can be avoided if we copy this file libomp140.x86_64.dll into c:\windows\system32
gen-ai commit: 1674f8065b8875ff5612f114adb500ed0a15307f

![image](https://github.com/user-attachments/assets/9fddd074-287f-4b29-9909-7ce849c506b3)

**Comment by eaidova** [comment]
Hello @avinashbhat09  this is known issue of pytorch ((do you use torch 2.4, correct?), You can find suggested solutions for that  on pytorch forum: https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

issue should be already fixed in torch 2.4.1, you can try to install the prerelease  torch version to get this fix or downgrade torch to lower versions where there is not such issue

**Comment by avinashbhat09** [comment]
Hi @eaidova : Can this be taken care in the requirements.txt? hardcode the torch version to be 2.4.1 or higher?

**Comment by eaidova** [comment]
@avinashbhat09 when 2.4.1 will be officially released then we do that, but for now, but for nowl we can only provide this info in known issues.
